version: '3.7'
services:
  postgres:
    container_name: pgvector_container
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: acme-assist
    ports:
      - "5433:5432"
