# Deploy with  tanzu apps workload create -f workload.yaml or kubectl apply -f workload.yaml
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: acme-catalog
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: acme-catalog
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  source:
    subPath: apps/acme-catalog
    git:
      url: https://github.com/spring-cloud-services-samples/acme-fitness-store/
      ref:
        branch: main
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  env:
    - name: spring.mvc.static-path-pattern
      value: /static/images/**
    - name: spring.web.resources.cache.cachecontrol.max-age
      value: "3600"
    - name: spring.web.resources.cache.cachecontrol.cache-public
      value: "true"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: acme-fitness-generic-test
    - name: ports
      value:
        - port: 80
          containerPort: 8080
          name: http
