server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-3.5-turbo
      api-key: ${OPENAI_API_KEY}
  application:
    name: acme-assist
  autoconfigure:
    exclude:
    - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  datasource:
    username: root
    password: rootpassword
    url: jdbc:postgresql://localhost:5433/acme-assist

vectorstore: postgres
