spring:
  application:
    name: acme-catalog
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    encoding: UTF-8
eureka:
  client:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,health
