name: Deploy Shopping
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - Azure
    paths:
      - 'apps/acme-shopping/**'
env:
  SPRING_APPS_SERVICE: ${{ secrets.SPRING_APPS_SERVICE }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  FRONTEND_APP: frontend

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/acme-shopping
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Build with Node.js
        run: npm install
      - run: npm run build --if-present
#TODO: no test
#      - run: npm test
      - name: Set up Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION }}
      - name: Set up Azure Spring Extension
        run: az extension add --name spring
      - name: Deploy Shopping
        run: |
          az spring app deploy \
            --name ${FRONTEND_APP} \
            --resource-group ${RESOURCE_GROUP} \
            --service ${SPRING_APPS_SERVICE} \
            --source-path ./
